# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20171107_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commenst_article',
            new_name='comments_article',
        ),
    ]
